const express = require('express')
const app = express()
const PORT =  process.env.PORT || 8000
const cors = require('cors')

app.use(cors())

app.get('/', (req,res) => {
     res.sendFile(__dirname + '/index.html')
 })



class States {
    constructor() {
        this.obj = arguments
    }
}

const alabama = new States(
    `Air University`,
    `Alabama A&M University`,
    `Alabama State University`,
    `Athens State University`,
    `Auburn University`,
    `Auburn University at Montgomery`,
    `Birmingham-Southern College`,
    `Concordia College-Selma`,
    `Faulkner University`,
    `Huntingdon College`,
    `Jacksonville State University`,
    `Judson College`,
    `Miles College`,
    `Oakwood College`,
    `Samford University`,
    `Southeastern Bible College`,
    `Southern Christian University`,
    `Spring Hill College`,
    `Stillman College`,
    `Talladega College`,
    `Troy State University (main campus)`,
    `Tuskegee University`,
    `United States Sports Academy`,
    `University of Alabama System`,
    `University of Mobile`,
    `University of Montevallo`,
    `University of North Alabama`,
    `University of South Alabama`,
    `University of West Alabama`
    )

const alaska = new States (
    `Alaska Bible College`,
    `Alaska Pacific University`,
    `Sheldon Jackson College`,
    `University of Alaska System`
)

const arizona = new States(
    `American Graduate School of International Management`,
    `American Indian College of the Assemblies of God`,
    `Arizona State University`,
    `Arizona State University East`,
    `Arizona State University West`,
    `DeVry University-Phoenix`,
    `Embry-Riddle Aeronautical University`,
    `Grand Canyon University`,
    `Northern Arizona University`,
    `Prescott College`,
    `Southwestern College`,
    `University of Arizona`,
    `University of Phoenix`,
    `Western International University`
)

const arkansas = new States(
    `Arkansas Baptist College`,
    `Arkansas State University, Jonesboro`,
    `Arkansas Tech University`,
    `Central Baptist College`,
    `Harding University`,
    `Henderson State University`,
    `Hendrix College`,
    `John Brown University`,
    `Lyon College`,
    `Ouachita Baptist University`,
    `Philander Smith College`,
    `Southern Arkansas University`,
    `University of Arkansas System`,
    `University of Central Arkansas`,
    `University of the Ozarks`,
    `Williams Baptist College`
)

const california = new States(
    `Alliant International University`,
    `Antioch University-Los Angeles`,
    `Art Center College of Design`,
    `Azusa Pacific University`,
    `Bethany College`,
    `Biola University`,
    `California Baptist University`,
    `California College of Arts & Crafts`,
    `California Institute of the Arts`,
    `California Institute of Integral Studies`,
    `California Institute of Technology`,
    `California Lutheran University`,
    `California National University`,
    `California Pacific University`,
    `California State University System`,
    `Chapman University`,
    `Christian Heritage College`,
    `Claremont Consortium of Colleges`,
    `Cogswell Polytechnical College`,
    `Concordia University-Irvine`,
    `Defense Language Institute`,
    `DeVry University-Long Beach`,
    `DeVry University-Pomona`,
    `Dominican University of California`,
    `Fielding Graduate Institute`,
    `Fresno Pacific University`,
    `Fuller Theological Seminary`,
    `Golden Gate University`,
    `Holy Names College`,
    `Hope International University`,
    `Humphreys College`,
    `Institute of Transpersonal Psychology`,
    `John F. Kennedy University`,
    `La Sierra University`,
    `Life Pacific College`,
    `Lincoln University`,
    `Loma Linda University`,
    `Loyola Marymount University`,
    `Marymount College`,
    `The Master's College`,
    `The Master's Seminary`,
    `Menlo College`,
    `Mills College`,
    `Monterey Institute of International Studies`,
    `Mount St. Mary's College`,
    `National Hispanic University`,
    `National University`,
    `Naval Postgraduate School`,
    `New College of California`,
    `Notre Dame de Namur University`,
    `Occidental College`,
    `Otis College of Art & Design`,
    `Pacific Oaks College`,
    `Pacific Union College`,
    `Pacifica Graduate Institute`,
    `Patten College`,
    `Pepperdine University`,
    `Platt College`,
    `Point Loma Nazarene College`,
    `Saint Mary's College of California`,
    `Samuel Merritt College`,
    `San Jose Christian College`,
    `Santa Clara University`,
    `Saybrook Graduate School & Research Center`,
    `Simpson College`,
    `Southern California Institute of Architecture`,
    `Southwestern University School of Law`,
    `Stanford University`,
    `Thomas Aquinas College`,
    `University of California System`,
    `University of Judaism`,
    `University of La Verne`,
    `University of Northern California`,
    `University of the Pacific`,
    `University of Redlands`,
    `University of San Diego`,
    `University of San Francisco`,
    `University of Southern California`,
    `University of West Los Angeles`,
    `Vanguard University of Southern California`,
    `Western State University College of Law`,
    `Western University of Health Sciences`,
    `Westminster Theological Seminary in California`,
    `Westmont College`,
    `Whittier College`,
    `William Howard Taft University`,
    `Woodbury University`
)

const colorado = new States(
    `Adams State College`,
    `Colorado Christian University`,
    `Colorado College`,
    `Colorado School of Mines`,
    `Colorado State University`,
    `Colorado Technical University`,
    `Fort Lewis College`,
    `Jones International University`,
    `Mesa State College`,
    `Metropolitan State College of Denver`,
    `Naropa Institute`,
    `National Technological University`,
    `Nazarene Bible College`,
    `Regis University`,
    `Rocky Mountain College of Art & Design`,
    `United States Air Force Academy`,
    `University of Colorado System`,
    `University of Denver`,
    `University of Northern Colorado`,
    `University of Southern Colorado`,
    `Western State College`
)

const connecticut = new States(
    `Albertus Magnus College`,
    `Central Connecticut State University`,
    `Charter Oak State College`,
    `Connecticut College`,
    `Eastern Connecticut State University`,
    `Fairfield University`,
    `Holy Apostles College & Seminary`,
    `Mitchell College`,
    `Quinnipiac College`,
    `Rensselaer at Hartford`,
    `Sacred Heart University`,
    `St. Joseph College`,
    `Southern Connecticut State University`,
    `Teikyo Post University`,
    `Trinity College`,
    `United States Coast Guard Academy`,
    `University of Bridgeport`,
    `University of Connecticut`,
    `University of Hartford`,
    `University of New Haven`,
    `Wesleyan University`,
    `Western Connecticut State University`,
    `Yale University`
)

const delaware = new States(
    `Delaware State University`,
    `Goldey-Beacom College`,
    `University of Delaware`,
    `Wesley College`,
    `Wilmington College`
)

const florida = new States(
    `The Baptist College of Florida`, 
    `Barry University`, 
    `Bethune-Cookman College`, 
    `Carlos Albizu University-Miami`, 
    `Clearwater Christian College`, 
    `DeVry University-Orlando`, 
    `Eckerd College`, 
    `Edward Waters College`, 
    `Embry-Riddle Aeronautical University`, 
    `Flagler College`, 
    `Florida Agricultural & Mechanical University`, 
    `Florida Atlantic University`, 
    `Florida Christian College`, 
    `Florida College`, 
    `Florida Gulf Coast University`, 
    `Florida Hospital College of Health Sciences`, 
    `Florida Institute of Technology`, 
    `Florida International University`, 
    `Florida Memorial College`, 
    `Florida Metropolitan University`, 
    `Florida Southern College`, 
    `Florida State University`, 
    `Hobe Sound Bible College`, 
    `International College`, 
    `International Fine Arts College`, 
    `Jacksonville University`, 
    `Jones College`, 
    `Lynn University`, 
    `Northwood University`, 
    `Nova Southeastern University`, 
    `Palm Beach Atlantic College`, 
    `Ringling School of Art & Design`, 
    `Rollins College`, 
    `Saint John Vianney College Seminary`, 
    `Saint Leo College`, 
    `St. Thomas University`, 
    `South Florida Bible College & Theological Seminary`, 
    `Southeastern College of the Assemblies of God`, 
    `Stetson University`, 
    `Trinity College of Florida`, 
    `Troy State University-Florida Region`, 
    `University of Central Florida`, 
    `University of Florida`, 
    `University of Miami`, 
    `University of North Florida`, 
    `University of South Florida`, 
    `University of Tampa`, 
    `University of West Florida`, 
    `Warner Southern College`, 
    `Webber College`
)

const georgia = new States(
`Agnes Scott College`, 
`American InterContinental University`, 
`Art Institute of Atlanta`, 
`Atlanta Christian College`, 
`Atlanta College of Art`, 
`Berry College`, 
`Brenau University`, 
`Brewton-Parker College`, 
`Clark Atlanta University`, 
`Covenant College`, 
`Dalton State College`, 
`Emmanuel College`, 
`Emory University`, 
`Institute of Paper Science & Technology`, 
`LaGrange College`, 
`Life University`, 
`Mercer University`, 
`Morehouse College`, 
`Morris Brown College`, 
`Oglethorpe University`, 
`Paine College`, 
`Piedmont College`, 
`Reinhardt College`, 
`Savannah College of Art & Design`, 
`Shorter College`, 
`South University`, 
`Spelman College`, 
`Thomas University`, 
`Toccoa Falls College`, 
`University System of Georgia`, 
`Wesleyan College`
)
const hawaii = new States(
    `Brigham Young University-Hawaii`,
    `Chaminade University`,
    `Hawaii Pacific University`,
    `University of Hawaii System`
)

const idaho = new States(
    `Albertson College of Idaho`, 
    `Boise State University`, 
    `Brigham Young University-Idaho`, 
    `Idaho State University`, 
    `Lewis-Clark State College`, 
    `Northwest Nazarene College`, 
    `University of Idaho`
)

const illinois = new States(
    `Augustana College`, 
    `Aurora University`, 
    `Barat College`, 
    `Benedictine University`, 
    `Blackburn College`, 
    `Bradley University`, 
    `The Chicago School of Professional Psychology`, 
    `Chicago State University`, 
    `College of DuPage`, 
    `Columbia College`, 
    `Concordia University-River Forest`, 
    `DePaul University`, 
    `DeVry University`, 
    `DeVry University-Chicago`, 
    `DeVry University-DuPage`, 
    `Dominican University`, 
    `East-West University`, 
    `Eastern Illinois University`, 
    `Elmhurst College`, 
    `Erikson Institute`, 
    `Eureka College`, 
    `Governors State University`, 
    `Greenville College`, 
    `Illinois College`, 
    `Illinois Institute of Technology`, 
    `Illinois State University`, 
    `Illinois Wesleyan University`, 
    `Judson College`, 
    `Kendall College`, 
    `Knox College`, 
    `Lake Forest College`, 
    `Lakeview College of Nursing`, 
    `Lewis University`, 
    `Lincoln Christian College & Seminary`, 
    `Loyola University Chicago`, 
    `Lutheran School of Theology at Chicago`, 
    `McKendree College`, 
    `McMurray College`, 
    `Midwestern University`, 
    `Millikin University`, 
    `Monmouth College`, 
    `Moody Bible Institute`, 
    `National University of Health Sciences`, 
    `National-Louis University`, 
    `North Central College`, 
    `North Park University`, 
    `Northeastern Illinois University`, 
    `Northern Illinois University`, 
    `Northwestern University`, 
    `Olivet Nazarene University`, 
    `Principia College`, 
    `Quincy University`, 
    `Robert Morris College`, 
    `Rockford College`, 
    `Roosevelt University`, 
    `Rush University`, 
    `Saint Anthony College of Nursing`, 
    `St. Xavier University`, 
    `School of the Art Institute of Chicago`, 
    `Shimer College`, 
    `Southern Illinois University System`, 
    `Spertus Institute of Jewish Studies`, 
    `Trinity Christian College`, 
    `Trinity International University`, 
    `University of Chicago`, 
    `University of Illinois System`, 
    `University of St. Francis`, 
    `Western Illinois University`, 
    `Wheaton College`
)

const indiana = new States (
    `Anderson University`, 
    `Ball State University`, 
    `Bethel College`, 
    `Butler University`, 
    `Calumet College of St. Joseph`, 
    `Christian Theological Seminary`, 
    `Concordia Theological Seminary-Fort Wayne`, 
    `DePauw University`, 
    `Earlham College`, 
    `Franklin College`, 
    `Goshen College`, 
    `Grace College`, 
    `Hanover College`, 
    `Holy Cross College`, 
    `Huntington College`, 
    `Indiana Institute of Technology`, 
    `Indiana State University`, 
    `Indiana University System`, 
    `Indiana Wesleyan University, Marion`, 
    `Manchester College`, 
    `Marian College`, 
    `Martin University`, 
    `Oakland City University`, 
    `Purdue University System`, 
    `Rose-Hulman Institute of Technology`, 
    `Saint Joseph's College`, 
    `Saint Mary-of-the-Woods College`, 
    `Saint Mary's College`, 
    `Taylor University`, 
    `Tri-State University`, 
    `University of Evansville`, 
    `University of Indianapolis`, 
    `University of Notre Dame`, 
    `University of Saint Francis`, 
    `University of Southern Indiana`, 
    `Valparaiso University`, 
    `Wabash College`
)

const iowa = new States(
    `Allen College`, 
    `Briar Cliff College`, 
    `Buena Vista University`, 
    `Central College`, 
    `Clarke College`, 
    `Coe College`, 
    `Cornell College`, 
    `Des Moines University-Osteopathic Medical Center`, 
    `Divine Word College`, 
    `Dordt College`, 
    `Drake University`, 
    `Emmaus Bible College`, 
    `Faith Baptist Bible College & Theological Seminary`, 
    `Graceland College`, 
    `Grand View College`, 
    `Grinnell College`, 
    `Iowa State University`, 
    `Iowa Wesleyan College`, 
    `Loras College`, 
    `Luther College`, 
    `Maharishi University of Management`, 
    `Marycrest International University`, 
    `Morningside College`, 
    `Mount Mercy College`, 
    `Mount St. Clare College`, 
    `Northwestern College of Iowa`, 
    `St. Ambrose University`, 
    `Simpson College`, 
    `University of Dubuque`, 
    `University of Iowa`, 
    `University of Northern Iowa`, 
    `Upper Iowa University`, 
    `Vennard College`, 
    `Waldorf College`, 
    `Wartburg College`, 
    `William Penn College`
)

const kansas = new States(
    `Baker University`, 
    `Barclay College`, 
    `Benedictine College`, 
    `Bethany College`, 
    `Bethel College`, 
    `Central Christian College`, 
    `Emporia State University`, 
    `Fort Hays State University`, 
    `Friends University`, 
    `Haskell Indian Nations University`, 
    `Hesston College`, 
    `Kansas State University`, 
    `Kansas Wesleyan University`, 
    `Manhattan Christian College`, 
    `McPherson College`, 
    `Mid-America Nazarene College`, 
    `Newman University`, 
    `Ottawa University`, 
    `Pittsburg State University`, 
    `Saint Mary College`, 
    `Southwestern College`, 
    `Sterling College`, 
    `Tabor College`, 
    `University of Kansas`, 
    `University of Kansas Medical Center`, 
    `Washburn University`, 
    `Wichita State University`
)

const kentucky = new States(
    `Alice Lloyd College`, 
    `Asbury College`, 
    `Asbury Theological Seminary`, 
    `Bellarmine College`, 
    `Berea College`, 
    `Brescia University`, 
    `Campbellsville University`, 
    `Centre College`, 
    `Clear Creek Baptist Bible College`, 
    `Cumberland College`, 
    `Eastern Kentucky University`, 
    `Georgetown College`, 
    `Kentucky Christian College`, 
    `Kentucky Mountain Bible College`, 
    `Kentucky State University`, 
    `Kentucky Wesleyan College`, 
    `Lindsey Wilson College`, 
    `Mid-Continent College`, 
    `Midway College`, 
    `Morehead State University`, 
    `Murray State University`, 
    `Northern Kentucky University`, 
    `Pikeville College`, 
    `Southern Baptist Theological Seminary`, 
    `Spalding University`, 
    `Sullivan University`, 
    `Thomas More College`, 
    `Transylvania University`, 
    `Union College`, 
    `University of Kentucky`, 
    `University of Louisville`, 
    `Western Kentucky University`
)

const louisiana = new States(
    `Centenary College of Louisiana`, 
    `Dillard University`, 
    `Grambling State University`, 
    `Louisiana College`, 
    `Louisiana State University System`, 
    `Louisiana Tech University`, 
    `Loyola University New Orleans`, 
    `McNeese State University`, 
    `Nicholls State University`, 
    `Northwestern State University of Louisiana`, 
    `Our Lady of Holy Cross College`, 
    `Our Lady of the Lake College`, 
    `Southeastern Louisiana University`, 
    `Southern University System`, 
    `Tulane University`, 
    `University of Louisiana System`, 
    `Xavier University of Louisiana`
)

const maine = new States(
    `Bates College`, 
    `Bowdoin College`, 
    `Colby College`, 
    `College of the Atlantic`, 
    `Husson College`, 
    `Maine College of Art`, 
    `Maine Maritime Academy`, 
    `St. Joseph's College`, 
    `Thomas College`, 
    `Unity College`, 
    `University of Maine System`, 
    `University of New England`
)

const maryland = new States(
    `Baltimore Hebrew University`, 
    `Baltimore International College`, 
    `Bowie State University`, 
    `Capitol College`, 
    `Chesapeake College`, 
    `College of Notre Dame of Maryland`, 
    `Columbia Union College`, 
    `Coppin State College`, 
    `Goucher College`, 
    `Frostburg State University`, 
    `Hood College`, 
    `Johns Hopkins University`, 
    `Loyola College`, 
    `Maryland institute, College of Art`, 
    `McDaniel College`, 
    `Morgan State University`, 
    `Mount Saint Mary's College`, 
    `St. John's College-Annapolis`, 
    `St. Mary's College of Maryland`, 
    `Salisbury State University`, 
    `Soujourner-Douglass College`, 
    `Towson University`, 
    `The Uniformed Services University of the Health Sciences`, 
    `United States Naval Academy`, 
    `University of Baltimore`, 
    `University of Maryland System`, 
    `Washington Bible College`, 
    `Washington College`, 
    `Villa Julie College`
)

const massachusetts = new States(
    `American International College`, 
    `Amherst College`, 
    `Anna Maria College`, 
    `Assumption College`, 
    `Atlantic Union College`, 
    `Babson College`, 
    `Bay Path College`, 
    `Becker College`, 
    `Benjamin Franklin Institute of Technology`, 
    `Bentley College`, 
    `Berklee College of Music`, 
    `Boston College`, 
    `Boston Conservatory`, 
    `Boston Graduate School of Psychoanalysis`, 
    `Boston University`, 
    `Brandeis University`, 
    `Bridgewater State College`, 
    `Cambridge College`, 
    `Clark University`, 
    `College of the Holy Cross`, 
    `Concord School of Management`, 
    `Curry College`, 
    `Eastern Nazarene College`, 
    `Elms College`, 
    `Emerson College`, 
    `Emmanuel College`, 
    `Endicott College`, 
    `Fitchburg State College`, 
    `Framingham State College`, 
    `Gordon College`, 
    `Gordon-Conwell Theological Seminary`, 
    `Hampshire College`, 
    `Harvard University`, 
    `Lasell College`, 
    `Lesley College`, 
    `Massachusetts College of Art`, 
    `Massachusetts College of Liberal Arts`, 
    `Massachuetts College of Pharmacy & Health Sciences`, 
    `Massachusetts Institute of Technology`, 
    `Massachusetts Maritime Academy`, 
    `Massachusetts School of Professional Psychology`, 
    `Merrimack College`, 
    `Mount Holyoke College`, 
    `Mount Ida College`, 
    `New England College of Optometry`, 
    `New England Conservatory of Music`, 
    `Newbury College`, 
    `Nichols College`, 
    `North Adams State College`, 
    `Northeastern University`, 
    `Pine Manor College`, 
    `Regis College`, 
    `Salem State College`, 
    `Simmons College`, 
    `Simon's Rock College`, 
    `Smith College`, 
    `Springfield College`, 
    `Stonehill College`, 
    `Suffolk University`, 
    `Tufts University`, 
    `University of Massachusetts System`, 
    `Wellesley College`, 
    `Wentworth Institute of Technology`, 
    `Western New England College`, 
    `Westfield State College`, 
    `Weston Jesuit School of Theology`, 
    `Wheaton College`, 
    `Wheelock College`, 
    `Williams College`, 
    `Worcester Polytechnic Institute`, 
    `Worcester State College`
)

const michigan = new States(
    `Adrian College`, 
    `Albion College`, 
    `Alma College`, 
    `Andrews University`, 
    `Aquinas College`, 
    `Baker College`, 
    `Calvin College`, 
    `Central Michigan University`, 
    `Cleary College`, 
    `College for Creative Studies`, 
    `Concordia College-Ann Arbor`, 
    `Cornerstone University`, 
    `Davenport University`, 
    `Eastern Michigan University`, 
    `Ferris State University`, 
    `Finlandia University`, 
    `Grace Bible College`, 
    `Grand Valley State University`, 
    `Hillsdale College`, 
    `Hope College`, 
    `Kalamazoo College`, 
    `Kendall College of Art & Design`, 
    `Kettering University`, 
    `Lake Superior State University`, 
    `Lawrence Technological University`, 
    `Madonna University`, 
    `Marygrove College`, 
    `Michigan State University`, 
    `Michigan Technological University`, 
    `Northern Michigan University`, 
    `Northwood University`, 
    `Oakland University`, 
    `Olivet College`, 
    `Reformed Bible College`, 
    `Rochester College`, 
    `Saginaw Valley State University`, 
    `Saint Mary's College`, 
    `Siena Heights University`, 
    `Spring Arbor University`, 
    `University of Detroit Mercy`, 
    `University of Michigan System`, 
    `Walsh College`, 
    `Wayne State University`, 
    `Western Michigan University`, 
    `William Tyndale College`
)

const minnesota = new States(
    `Alfred Adler Institute`, 
    `Augsburg College`, 
    `Bethany Lutheran College`, 
    `Bethel College and Seminary`, 
    `Capella University`, 
    `Carleton College`, 
    `College of Saint Benedict`, 
    `College of St. Catherine`, 
    `College of St. Scholastica`, 
    `College of Visual Arts`, 
    `Concordia College-Moorhead`, 
    `Concordia College-St. Paul`, 
    `Crossroads College`, 
    `Crown College`, 
    `Gustavus Adolphus College`, 
    `Hamline University`, 
    `Luther Seminary`, 
    `Macalester College`, 
    `Martin Luther College`, 
    `Minneapolis College of Art & Design`, 
    `Minnesota State University System`, 
    `North Central University`, 
    `Northwest College, Wyoming`, 
    `Oak Hills Christian College`, 
    `Pillsbury Baptist Bible College`, 
    `Saint John's University`, 
    `Saint Mary's University of Minnesota`, 
    `Saint Olaf College`, 
    `University of Minnesota System`, 
    `University of Saint Thomas`, 
    `Walden University`, 
    `William Mitchell College of Law`
)

const mississippi = new States(
    `Alcorn State University`, 
    `Belhaven College`, 
    `Blue Mountain College`, 
    `Delta State University`, 
    `Jackson State University`, 
    `Magnolia Bible College`, 
    `Millsaps College`, 
    `Mississippi College`, 
    `Mississippi State University`, 
    `Mississippi University for Women`, 
    `Mississippi Valley State University`, 
    `Rust College`, 
    `Tougaloo College`, 
    `University of Mississippi`, 
    `University of Mississippi Medical Center`, 
    `University of Southern Mississippi`, 
    `William Carey College`
)

const missouri = new States(
    `Avila College`, 
    `Baptist Bible College`, 
    `Central Bible College`, 
    `Central Christian College of the Bible`, 
    `Central Methodist College`, 
    `Central Missouri State University`, 
    `Cleveland Chiropractic College`, 
    `College of the Ozarks`, 
    `Columbia College`, 
    `Concordia Seminary-St. Louis`, 
    `Culver-Stockton College`, 
    `DeVry University-Kansas City`, 
    `Drury University`, 
    `Evangel University`, 
    `Fontbonne College`, 
    `Forest Institute of Professional Psychology`, 
    `Greenleaf University`, 
    `Hannibal-Lagrange College`, 
    `Harris-Stowe State College`, 
    `Kirksville College of Osteopathic Medicine`, 
    `Lincoln University`, 
    `Lindenwood University`, 
    `Logan College of Chiropractic`, 
    `Maryville University of St. Louis`, 
    `Missouri Baptist College`, 
    `Missouri Southern State College`, 
    `Missouri Valley College`, 
    `Missouri Western State College`, 
    `Northwest Missouri State University`, 
    `Ozark Christian College`, 
    `Park University`, 
    `Rockhurst University`, 
    `St. Louis College of Pharmacy`, 
    `Saint Louis University`, 
    `Southeast Missouri State University`, 
    `Southwest Baptist University`, 
    `Southwest Missouri State University`, 
    `Stephens College`, 
    `Truman State University`, 
    `University of Missouri System`, 
    `Washington University, St. Louis`, 
    `Webster University`, 
    `Westminster College`, 
    `William Jewell College`, 
    `William Woods University`
)
const montana = new States(
    `Carroll College`, 
    `Montana State University System`, 
    `Rocky Mountain College`, 
    `Salish Kootenai College`, 
    `University of Great Falls`, 
    `University of Montana System` 
)

const nebraska = new States(
    `Bellevue University`, 
    `Chadron State College`, 
    `Clarkson College`, 
    `College of Saint Mary`, 
    `Concordia University-Nebraska`, 
    `Creighton University`, 
    `Dana College`, 
    `Doane College`, 
    `Grace University`, 
    `Hastings College`, 
    `Midland Lutheran College`, 
    `Nebraska Christian College`, 
    `Nebraska Methodist College`, 
    `Nebraska Wesleyan University`, 
    `Peru State College`, 
    `Union College`, 
    `University of Nebraska System`, 
    `Wayne State College`, 
    `York College`
)

const nevada = new States(
    `Sierra Nevada College`,
    `University of Nevada System`
)

const newhampshire = new States(
    `Antioch New England`, 
    `Colby-Sawyer College`, 
    `College for Lifelong Learning`, 
    `Daniel Webster College`, 
    `Dartmouth College`, 
    `Franklin Pierce College`, 
    `Franklin Pierce Law Center`, 
    `Keene State College`, 
    `New England College`, 
    `New Hampshire College`, 
    `Notre Dame College`, 
    `Plymouth State College`, 
    `Rivier College`, 
    `Saint Anselm College`, 
    `Southern New Hampshire University`, 
    `The Thomas More College of Liberal Arts`, 
    `University of New Hampshire`, 
    `University of New Hampshire at Manchester`, 
    `White Pines College`
)

const newjersey = new States(
    `Berkeley College`, 
    `Bloomfield College`, 
    `Caldwell College`, 
    `Centenary College`, 
    `The College of New Jersey`, 
    `College of Saint Elizabeth`, 
    `Drew University`, 
    `Fairleigh Dickinson University`, 
    `Felician College`, 
    `Georgian Court College`, 
    `Kean University`, 
    `Monmouth University`, 
    `Montclair State University`, 
    `New Jersey City University`, 
    `New Jersey Institute of Technology`, 
    `Princeton University`, 
    `Ramapo College`, 
    `Richard Stockton College of New Jersey`, 
    `Rider University`, 
    `Rowan University`, 
    `Rutgers University`, 
    `Saint Peter's College`, 
    `Seton Hall University`, 
    `Stevens Institute of Technology`, 
    `Thomas Edison State College`, 
    `University of Medicine & Dentistry of New Jersey`, 
    `William Paterson University`
)

const newmexico = new States(
    `College of Santa Fe`, 
    `College of the Southwest`, 
    `Eastern New Mexico University`, 
    `New Mexico Institute of Mining & Technology`, 
    `New Mexico Highlands University`, 
    `New Mexico State University`, 
    `St. John's College-Santa Fe`, 
    `University of New Mexico`, 
    `Western New Mexico University` 
)

const newyork = new States(
    `Adelphi University`, 
    `Albany College of Pharmacy`, 
    `Albany Medical College`, 
    `Alfred University`, 
    `Bank Street College of Education`, 
    `Bard College`, 
    `Barnard College`, 
    `Boricua College`, 
    `Canisius College`, 
    `Cazenovia College`, 
    `City University of New York System`, 
    `Clarkson University`, 
    `Colgate University`, 
    `College of Aeronautics`, 
    `College of Mount St. Vincent`, 
    `College of New Rochelle`, 
    `College of Saint Rose`, 
    `Columbia University`, 
    `Concordia College-Bronxville`, 
    `The Cooper Union for the Advancement of Science & Art`, 
    `Cornell University`, 
    `Daemen College`, 
    `Dominican College`, 
    `Dowling College`, 
    `D?Youville College`, 
    `Elmira College`, 
    `Excelsior College`, 
    `Five Towns College`, 
    `Fordham University`, 
    `Hamilton College`, 
    `Hartwick College`, 
    `Hebrew Union College-Jewish Institute of Religion`, 
    `Hilbert College`, 
    `Hobart and William Smith Colleges`, 
    `Hofstra University`, 
    `Houghton College`, 
    `Iona College`, 
    `Ithaca College`, 
    `The Jewish Theological Seminary of America`, 
    `The Juilliard School`, 
    `Keuka College`, 
    `Le Moyne College`, 
    `Laboratory Institute of Merchandising`, 
    `Long Island University`, 
    `Manhattan College`, 
    `Manhattan School of Music`, 
    `Manhattanville College`, 
    `Marist College`, 
    `Marymount College`, 
    `Marymount Manhattan College`, 
    `Medaille College`, 
    `Mercy College`, 
    `Metropolitan College of New York`, 
    `Molloy College`, 
    `Monroe College`, 
    `Mount Saint Mary College`, 
    `Nazareth College`, 
    `New School University`, 
    `New York College of Podiatric Medicine`, 
    `New York Institute of Technology`, 
    `New York Medical College`, 
    `New York University`, 
    `Niagara University`, 
    `Nyack College`, 
    `Pace University`, 
    `Parsons School of Design`, 
    `Paul Smith's College`, 
    `Polytechnic University of New York`, 
    `Pratt Institute`, 
    `Rensselaer Polytechnic Institute`, 
    `Roberts Wesleyan College`, 
    `Rochester Institute of Technology`, 
    `The Rockefeller University`, 
    `The Sage Colleges`, 
    `St. Bonaventure University`, 
    `Saint Francis College`, 
    `St. John Fisher College`, 
    `St. John's University`, 
    `St. Joseph's College`, 
    `St. Lawrence University`, 
    `St. Thomas Aquinas College`, 
    `Sarah Lawrence College`, 
    `School of Visual Arts`, 
    `Siena College`, 
    `Skidmore College`, 
    `State University of New York System`, 
    `Syracuse University`, 
    `Teachers College, Columbia University`, 
    `Touro College`, 
    `Unification Theological Seminary`, 
    `Union College`, 
    `Union Theological Seminary`, 
    `United States Merchant Marine Academy`, 
    `United States Military Academy`, 
    `University of Rochester`, 
    `Utica College of Syracuse University`, 
    `Vassar College`, 
    `Wagner College`, 
    `Webb Institute`, 
    `Wells College`, 
    `Yeshiva University`
)

const northcarolina = new States(
    `Appalachian State University`, 
    `Barber-Scotia College`, 
    `Barton College`, 
    `Belmont Abbey College`, 
    `Bennett College`, 
    `Brevard College`, 
    `Campbell University`, 
    `Catawba College`, 
    `Chowan College`, 
    `Davidson College`, 
    `Duke University`, 
    `East Carolina University`, 
    `Elizabeth City State University`, 
    `Elon University`, 
    `Fayetteville State University`, 
    `Gardner-Webb University`, 
    `Greensboro College`, 
    `Guilford College`, 
    `High Point University`, 
    `Johnson C. Smith University`, 
    `Lees-McRae College`, 
    `Lenoir-Rhyne College`, 
    `Livingstone College`, 
    `Louisburg College`, 
    `Mars Hill College`, 
    `Meredith College`, 
    `Methodist College`, 
    `Montreat College`, 
    `Mount Olive College`, 
    `North Carolina Central University`, 
    `North Carolina A&T State University`, 
    `North Carolina School of the Arts`, 
    `North Carolina State University`, 
    `North Carolina Wesleyan College`, 
    `Peace College`, 
    `Pfeiffer University`, 
    `Piedmont Baptist College`, 
    `Queens University of Charlotte`, 
    `Roanoke Bible College`, 
    `St. Andrews Presbyterian College`, 
    `St. Augustine's College`, 
    `Salem College`, 
    `Shaw University`, 
    `University of North Carolina System`, 
    `Wake Forest University`, 
    `Warren Wilson College`, 
    `Western Carolina University`, 
    `Wingate University`, 
    `Winston-Salem State University`
)

const northdakota = new States(
    `Dickinson State University`, 
    `Jamestown College`, 
    `Mayville State University`, 
    `Minot State University`, 
    `North Dakota State University`, 
    `Trinity Bible College`, 
    `University of Mary`, 
    `University of North Dakota`, 
    `Valley City State University`
)

const ohio = new States(
    `Air Force Institute of Technology`, 
    `Antioch College`, 
    `Art Academy of Cincinnati`, 
    `Ashland University`, 
    `Baldwin-Wallace College`, 
    `Bowling Green State University`, 
    `Bluffton College`, 
    `Capital University`, 
    `Case Western Reserve University`, 
    `Cedarville University`, 
    `Central State University`, 
    `Cincinnati Bible College & Seminary`, 
    `Circleville Bible College`, 
    `Cleveland Institute of Art`, 
    `Cleveland Institute of Music`, 
    `Cleveland State University`, 
    `College of Mount St. Joseph`, 
    `The College of Wooster`, 
    `Columbus College of Art & Design`, 
    `Chancellor University`, 
    `Jack Welch Management Institute`, 
    `Defiance College`, 
    `Denison University`, 
    `Franciscan University of Steubenville`, 
    `Franklin University`, 
    `Heidelberg College`, 
    `Hiram College`, 
    `John Carroll University`, 
    `Kent State University`, 
    `Kenyon College`, 
    `Lake Erie College`, 
    `Laura & Alvin Siegal College of Judaic Studies`, 
    `Lourdes College`, 
    `Malone College`, 
    `Marietta College`, 
    `Medical College of Ohio`, 
    `Miami University of Ohio`, 
    `Mount Union College`, 
    `Mount Vernon Nazarene College`, 
    `Muskingum College`, 
    `Northeastern Ohio Universities College of Medicine`, 
    `Notre Dame College`, 
    `Oberlin College`, 
    `Ohio Dominican College`, 
    `Ohio Northern University`, 
    `Ohio State University System`, 
    `Ohio Wesleyan University`, 
    `Ohio University, Athens`, 
    `Otterbein College`, 
    `Shawnee State University`, 
    `Tiffin University`, 
    `Union Institute & University`, 
    `University of Akron`, 
    `University of Cincinnati`, 
    `University of Dayton`, 
    `The University of Findlay`, 
    `University of Northwestern Ohio`, 
    `University of Rio Grande`, 
    `University of Toledo`, 
    `Urbana University`, 
    `Ursuline College`, 
    `Walsh University`, 
    `Wilberforce University`, 
    `Wilmington College`, 
    `Wittenberg University`, 
    `Wright State University`, 
    `Xavier University`, 
    `Youngstown State University`
)

const oklahoma = new States(
    `Bacone College`, 
    `Cameron University`, 
    `East Central University`, 
    `Langston University`, 
    `Mid-America Bible College`, 
    `Northeastern State University`, 
    `Northwestern Oklahoma State University`, 
    `Oklahoma Baptist University`, 
    `Oklahoma Christian University of Science & Arts`, 
    `Oklahoma City University`, 
    `Oklahoma Panhandle State University`, 
    `Oklahoma State University`, 
    `Oklahoma Wesleyan University`, 
    `Oral Roberts University`, 
    `Phillips University (closed July 1998)`, 
    `Rogers State University`, 
    `St. Gregory's University`, 
    `Southeastern Oklahoma State University`, 
    `Southern Nazarene University`, 
    `Southwestern Oklahoma State University`, 
    `University of Central Oklahoma`, 
    `University of Oklahoma`, 
    `University of Oklahoma Health Sciences Center`, 
    `University of Science & Arts of Oklahoma`, 
    `University of Tulsa`
)

const oregon = new States(
    `Concordia University-Portland`, 
    `Eastern Oregon University`, 
    `Eugene Bible College`, 
    `George Fox University`, 
    `Gutenberg College`, 
    `Lewis & Clark College`, 
    `Linfield College`, 
    `Marylhurst University`, 
    `Mount Angel Seminary`, 
    `Multnomah Bible College & Seminary`, 
    `Northwest Christian College`, 
    `Oregon Graduate Institute of Science & Technology`, 
    `Oregon Health Sciences University`, 
    `Oregon Institute of Technology`, 
    `Oregon State University`, 
    `Pacific Northwest College of Art`, 
    `Pacific University`, 
    `Portland State University`, 
    `Reed College`, 
    `Southern Oregon University`, 
    `University of Oregon`, 
    `University of Portland`, 
    `Warner Pacific College`, 
    `Western Baptist College`, 
    `Western Oregon University`, 
    `Western States Chiropractic College`, 
    `Willamette University`
)

const pennsylvania = new States(
    `Albright College`, 
    `Allegheny College`, 
    `Alvernia College`, 
    `American College`, 
    `Arcadia University`, 
    `Baptist Bible College`, 
    `Bloomsburg University of Pennsylvania`, 
    `Bryn Athyn College of the New Church`, 
    `Bryn Mawr College`, 
    `Bucknell University`, 
    `Cabrini College`, 
    `California University of Pennsylvania`, 
    `Carlow College`, 
    `Carnegie Mellon University`, 
    `Cedar Crest College`, 
    `Chatham College`, 
    `Chestnut Hill College`, 
    `Cheyney University`, 
    `Clarion University of Pennsylvania`, 
    `College Misericordia`, 
    `Curtis Institute of Music`, 
    `Delaware Valley College`, 
    `DeSales University`, 
    `Dickinson College`, 
    `Drexel University`, 
    `Duquesne University`, 
    `East Stroudsburg University of Pennsylvania`, 
    `Eastern College`, 
    `Edinboro University of Pennsylvania`, 
    `Elizabethtown College`, 
    `Franklin & Marshall College`, 
    `Gannon University`, 
    `Geneva College`, 
    `Gettysburg College`, 
    `Gratz College`, 
    `Grove City College`, 
    `Gwynedd Mercy College`, 
    `Haverford College in Pennsylvania`, 
    `Holy Family College`, 
    `Immaculata College`, 
    `Indiana University of Pennsylvania`, 
    `Juniata College`, 
    `Keystone College`, 
    `Kings College`, 
    `Kutztown University of Pennsylvania`, 
    `La Roche College`, 
    `Lafayette College`, 
    `Lancaster Bible College`, 
    `LaSalle University`, 
    `Lebanon Valley College`, 
    `Lehigh University`, 
    `Lincoln University`, 
    `Lock Haven University of Pennsylvania`, 
    `Lycoming College`, 
    `Mansfield University of Pennsylvania`, 
    `Marywood University`, 
    `Mercyhurst College`, 
    `Messiah College`, 
    `Millersville University of Pennsylvania`, 
    `Moore College of Art & Design`, 
    `Moravian College`, 
    `Mount Aloysius College`, 
    `Muhlenberg College`, 
    `Neumann College`, 
    `Peirce College`, 
    `Pennsylvania College of Optometry`, 
    `Pennsylvania State University System`, 
    `Philadelphia Biblical University`, 
    `Philadelphia College of Pharmacy & Science`, 
    `Philadelphia University`, 
    `Point Park Morris College`, 
    `Robert Morris College`, 
    `Rosemont College`, 
    `Saint Francis College`, 
    `Saint Joseph's University`, 
    `Saint Vincent College`, 
    `Seton Hill College`, 
    `Shippensburg University of Pennsylvania`, 
    `Slippery Rock University of Pennsylvania`, 
    `Susquehanna University`, 
    `Swarthmore College`, 
    `Temple University`, 
    `Thiel College`, 
    `Thomas Jefferson University`, 
    `University of Pennsylvania`, 
    `University of Pittsburgh`, 
    `University of Scranton`, 
    `University of the Arts`, 
    `University of the Sciences in Philadelphia`, 
    `Ursinus College`, 
    `Valley Forge Christian College`, 
    `Villanova University`, 
    `Washington and Jefferson College`, 
    `Waynesburg College`, 
    `West Chester University of Pennsylvania`, 
    `Westminster College`, 
    `Westminster Theological Seminary`, 
    `Widener University`, 
    `Wilkes University`, 
    `Wilson College`, 
    `York College of Pennsylvania`
)

const rhodeisland = new States(
    `Brown University`, 
    `Bryant College`, 
    `Johnson & Wales University`, 
    `Naval War College`, 
    `New England Institute of Technology`, 
    `Providence College`, 
    `Rhode Island College`, 
    `Rhode Island School of Design`, 
    `Roger Williams University`, 
    `Salve Regina University`, 
    `University of Rhode Island`
)

const southcarolina = new States(
    `Allen University`, 
    `Anderson College`, 
    `Benedict College`, 
    `Bob Jones University`, 
    `Charleston Southern University`, 
    `The Citadel`, 
    `Claflin University`, 
    `Clemson University`, 
    `Coastal Carolina University`, 
    `Coker College`, 
    `College of Charleston`, 
    `Columbia College`, 
    `Columbia International University`, 
    `Converse College`, 
    `Erskine College`, 
    `Francis Marion University`, 
    `Furman University`, 
    `Johnson & Wales University-Charleston`, 
    `Lander University`, 
    `Limestone College`, 
    `Medical University of South Carolina`, 
    `Morris College`, 
    `Newberry College`, 
    `North Greenville College`, 
    `Presbyterian College`, 
    `Sherman College of Straight Chiropractic`, 
    `South Carolina State University`, 
    `Southern Wesleyan University`, 
    `University of South Carolina System`, 
    `Voorhees College`, 
    `Winthrop University`, 
    `Wofford College`
)

const southdakota = new States(
    `Augustana College`, 
    `Black Hills State University`, 
    `Dakota State University`, 
    `Dakota Wesleyan University`, 
    `Mount Marty College`, 
    `National American University`, 
    `Northern State University`, 
    `Oglala Lakota College`, 
    `Presentation College`, 
    `Sinte Gleska University`, 
    `South Dakota School of Mines & Technology`, 
    `South Dakota State University`, 
    `University of Sioux Falls`, 
    `University of South Dakota`
)

const tennessee = new States(
    `Aquinas College`, 
    `Austin Peay State University`, 
    `Baptist Memorial College of Health Sciences`, 
    `Belmont University`, 
    `Bethel College`, 
    `Bryan College`, 
    `Carson-Newman College`, 
    `Christian Brothers University`, 
    `Church of God Theological Seminary`, 
    `Crichton College`, 
    `Cumberland University`, 
    `East Tennessee State University`, 
    `Fisk University`, 
    `Freed-Hardeman University`, 
    `Johnson Bible College`, 
    `King College`, 
    `Knoxville College`, 
    `Lambuth University`, 
    `Lane College`, 
    `Lee University`, 
    `LeMoyne-Owen College`, 
    `Lincoln Memorial University`, 
    `Lipscomb University`, 
    `Martin Methodist College`, 
    `Maryville College`, 
    `Meharry Medical College`, 
    `Memphis College of Art`, 
    `Middle Tennessee State University`, 
    `Milligan College`, 
    `Rhodes College`, 
    `Southern Adventist University`, 
    `Southern College`, 
    `Southern College of Optometry`, 
    `Tennessee State University`, 
    `Tennessee Technological University`, 
    `Tennessee Temple University`, 
    `Tennessee Wesleyan College`, 
    `Trevecca Nazarene University`, 
    `Tusculum College`, 
    `Union University`, 
    `University of Memphis`, 
    `University of Tennessee System`, 
    `University of the South`, 
    `Vanderbilt University`
)


const texas = new States(
    `Abilene Christian University`, 
    `Amberton University`, 
    `Angelo State University`, 
    `Arlington Baptist College`, 
    `Art Institute of Dallas`, 
    `Austin College`, 
    `Austin Presbyterian Theological Seminary`, 
    `Baylor College of Medicine`, 
    `Baylor University`, 
    `College of Saint Thomas More`, 
    `Concordia University-Austin`, 
    `Criswell College`, 
    `Dallas Baptist University`, 
    `Dallas Christian College`, 
    `Dallas Theological Seminary`, 
    `DeVry University-Dallas`, 
    `East Texas Baptist University`, 
    `Episcopal Theological Seminary of the Southwest`, 
    `Hardin-Simmons University`, 
    `Houston Baptist University`, 
    `Howard Payne University`, 
    `Huston-Tillotson College`, 
    `Institute for Christian Studies`, 
    `ICI University`, 
    `Jarvis Christian College`, 
    `Lamar University`, 
    `LeTourneau University`, 
    `Lubbock Christian University`, 
    `McMurry University`, 
    `Midwestern State University`, 
    `Northwood University`, 
    `Our Lady of the Lake University`, 
    `Parker College of Chiropractic`, 
    `Paul Quinn College`, 
    `Rice University`, 
    `St. Edward's University`, 
    `Saint Mary's University of San Antonio`, 
    `Sam Houston State University`, 
    `Schreiner College`, 
    `Southern Methodist University`, 
    `South Texas College of Law`, 
    `Southwest Texas State University`, 
    `Southwestern Adventist University`, 
    `Southwestern Assemblies of God University`, 
    `Southwestern Baptist Theological Seminary`, 
    `Southwestern Christian College`, 
    `Southwestern University`, 
    `Stephen F. Austin State University`, 
    `Sul Ross State University`, 
    `Texas A&M University System`, 
    `Texas Chiropractic College`, 
    `Texas Christian University`, 
    `Texas College`, 
    `Texas Lutheran University`, 
    `Texas Southern University`, 
    `Texas Tech University`, 
    `Texas Tech University-Health Sciences Center`, 
    `Texas Wesleyan University`, 
    `Texas Woman's University`, 
    `Trinity University`, 
    `University of Dallas`, 
    `University of Houston System`, 
    `University of Mary Hardin-Baylor`, 
    `University of North Texas`, 
    `University of North Texas Health Science Center`, 
    `University of Saint Thomas`, 
    `University of Texas System`, 
    `University of the Incarnate Word`, 
    `Wayland Baptist University`, 
    `Wiley College`
)

const utah = new States(
    `Brigham Young University`, 
    `College of Eastern Utah`, 
    `Southern Utah University`, 
    `University of Utah`, 
    `Utah State University`, 
    `Utah Valley State College`, 
    `Weber State University`, 
    `Westminster College`
)

const vermont = new States(
    `Bennington College`, 
    `Burlington College`, 
    `Castleton State University`, 
    `Champlain College`, 
    `College of St. Joseph`, 
    `Goddard College`, 
    `Green Mountain College`, 
    `Johnson State College`, 
    `Lyndon State College`, 
    `Marlboro College`, 
    `Middlebury College`, 
    `Norwich University`, 
    `Saint Michael's College`, 
    `School for International Training`, 
    `Southern Vermont College`, 
    `Trinity College`, 
    `University of Vermont`, 
    `Vermont Law School`, 
    `Vermont Technical College`
)
const viginia = new States(
    `Averett College`, 
    `Bluefield College`, 
    `Bridgewater College`, 
    `Christendom College`, 
    `Christopher Newport University`, 
    `College of Health Sciences`, 
    `College of William and Mary`, 
    `Eastern Mennonite University`, 
    `Eastern Virginia Medical School`, 
    `Emory & Henry College`, 
    `Ferrum College`, 
    `George Mason University`, 
    `George Washington University-Virginia Campus`, 
    `Hampden-Sydney College`, 
    `Hampton University`, 
    `Hollins University`, 
    `Institute of Textile Technology`, 
    `James Madison University`, 
    `Liberty University`, 
    `Longwood University`, 
    `Lynchburg College`, 
    `Marine Corps University`, 
    `Mary Baldwin College`, 
    `Marymount University`, 
    `Mary Washington College`, 
    `Norfolk State University`, 
    `Old Dominion University`, 
    `Radford University`, 
    `Randolph-Macon College`, 
    `Randolph-Macon Woman's College`, 
    `Regent University`, 
    `Roanoke College`, 
    `Saint Paul's College`, 
    `Shenandoah University`, 
    `Southern Virginia College`, 
    `Sweet Briar College`, 
    `University of Richmond`, 
    `University of Virginia`, 
    `University of Virginia's College at Wise`, 
    `Virginia Commonwealth University`, 
    `Virginia Intermont College`, 
    `Virginia Military Institute`, 
    `Virginia Polytechnic Institute and State University`, 
    `Virginia State University`, 
    `Virginia Union University`, 
    `Virginia Wesleyan College`, 
    `Washington Bible College/Capital Bible Seminary`, 
    `Washington & Lee University`
)

const washington = new States(
    `Antioch University-Seattle`, 
    `Art Institute of Seattle`, 
    `Bastyr University`, 
    `Central Washington University`, 
    `City University`, 
    `Eastern Washington University`, 
    `Evergreen State College`, 
    `Gonzaga University`, 
    `Henry Cogswell College`, 
    `Heritage College`, 
    `Northwest College of the Assemblies of God`, 
    `Pacific Lutheran University`, 
    `St. Martin's College`, 
    `Seattle Pacific University`, 
    `Seattle University`, 
    `Trinity Lutheran College`, 
    `University of Puget Sound`, 
    `University of Washington`, 
    `University of Washington-Bothell`, 
    `University of Washington-Tacoma`, 
    `Walla Walla College`, 
    `Washington State University at Pullman`, 
    `Washington State University at Spokane`, 
    `Washington State University at Tri-Cities`, 
    `Washington State University at Vancouver`, 
    `Western Washington University`, 
    `Whitman College`, 
    `Whitworth College`
)

const westvirginia = new States(
    `Alderson-Broaddus College`, 
    `Bethany College`, 
    `Bluefield State College`, 
    `Concord College`, 
    `Davis & Elkins College`, 
    `Fairmont State College`, 
    `Glenville State College`, 
    `Marshall University`, 
    `Mountain State University`, 
    `Ohio Valley College`, 
    `Salem International University`, 
    `Shepherd College`, 
    `University of Charleston`, 
    `West Liberty University`, 
    `West Virginia State College`, 
    `West Virginia University`, 
    `West Virginia University Institute of Technology`, 
    `West Virginia University at Parkersburg`, 
    `West Virginia Wesleyan College`, 
    `Wheeling Jesuit University`
)

const wisconsin = new States(
    `Alverno College`, 
    `Beloit College`, 
    `Cardinal Stritch College`, 
    `Carroll College`, 
    `Carthage College`, 
    `Concordia University-Wisconsin`, 
    `Edgewood College`, 
    `Lakeland College`, 
    `Lawrence University`, 
    `Maranatha Baptist Bible College`, 
    `Marian College of Fond du Lac`, 
    `Marquette University`, 
    `Medical College of Wisconsin`, 
    `Milwaukee School of Engineering`, 
    `Mount Mary College`, 
    `Mount Senario College`, 
    `Northland College`, 
    `Ripon College`, 
    `St. Norbert College`, 
    `Silver Lake College`, 
    `University of Wisconsin System`, 
    `Viterbo College`, 
    `Wisconsin Lutheran College`, 
    `Wisconsin School of Professional Psychology`
)

const wyoming = new States(
    `University of Wyoming` 
)


const stateObj = {
     'alabama' : {alabama}, 
      'alaska': {alaska}, 
      'arizona': {arizona}, 
      'arkansas': {arkansas}, 
      'california': {california}, 
      'colorado': {colorado}, 
      'connecticut': {connecticut}, 
      'delaware': {delaware}, 
      'florida': {florida}, 
      'georgia': {georgia}, 
      'hawaii': {hawaii}, 
      'idaho': {idaho}, 
      'illinois': {illinois}, 
      'indiana': {indiana}, 
      'iowa': {iowa}, 
      'kansas': {kansas}, 
      'kentucky': {kentucky}, 
      'louisiana': {louisiana}, 
      'maine': {maine}, 
      'maryland': {maryland}, 
      'massachusetts': {massachusetts}, 
      'michigan': {michigan}, 
      'minnesota': {minnesota}, 
      'missouri': {missouri}, 
      'montana': {montana}, 
      'nebraska': {nebraska}, 
      'nevada': {nevada}, 
      'new hampshire': {newhampshire}, 
      'new jersey': {newjersey}, 
      'new mexico': {newmexico}, 
      'north carolina': {northcarolina}, 
      'north dakota': {northdakota}, 
      'oklahoma': {oklahoma}, 
      'ohio': {ohio}, 
      'oregon': {oregon}, 
      'pennsylvania': {pennsylvania}, 
      'rhode island': {rhodeisland}, 
      'south carolina': {southcarolina}, 
      'south dakota': {southdakota}, 
      'tennessee': {tennessee}, 
      'texas': {texas}, 
      'utah': {utah}, 
      'vermont': {vermont}, 
      'viginia': {viginia}, 
      'washington': {washington}, 
      'west virginia': {westvirginia}, 
      'wisconsin': {wisconsin}, 
      'wyoming': {wyoming},
    'unknown' : {
         1 : "Request unknown, please use a valid state name"
     }
}



app.get('/api/:state', (req,res) => {
    const state = req.params.state.toLowerCase()
    if (stateObj[state]){
        res.json(stateObj[state])
    } else {
        res.json(stateObj[`unknown`])
    }
})


app.listen(  PORT, function () {
    console.log('server is running...')
})